### ISSUE TITLE
Идея

### ISSUE THREAD

**Issue by kvrvgv** [mrgick/rasp_pskgu#6]
Часто расписание неофициально меняют, было бы круто чтобы студенты могли прямо в таблице нажать на какой-нибудь значок и посмотреть, вдруг перенесена/отменена/пары для 1пг и 2пг обьеденены и тд, что-то типа заметок. Думаю это очень удобная функция, главное чтобы эти заметки кто-нибудь заполнял, мб старосты будут этим заниматься или нет.

**Comment by WhiteRain7** [comment]
Здравствуйте. Ваша идея уже отчасти реализована с помощью "событий", добавленных в обновлении 1.2.0 около месяца назад. С их помощью, любой человек может добавить событие, указав название и описание, на любой день и пару, и оно будет отображаться в расписании снизу отмеченной пары. Созданными событиями можно поделиться с помощью специальной ссылки. Например:
https://mrgick.github.io/rasp_pskgu/index.html?event=Rfr0rgrr0aESrdr50aESr1rjr4r5ri0b0b010606ET0200020200050207040b00

Подробнее о том, как добавлять события и делиться ими - в руководстве "Использование событий", которое Вы можете найти во вкладке "Справка" в меню действий (справа сверху), только на странице с расписанием.

![image](https://user-images.githubusercontent.com/74417675/170479781-e905ecac-ddf9-4ded-999d-473b6db96823.png)
![image](https://user-images.githubusercontent.com/74417675/170480300-ba17db52-489e-4de5-b33a-f82af54f2000.png)
